


export const story1 = `

Another day, another near-miss. 

I know the Earth is spinning down there. It's that bright, blue-and-white marble, perpetually orbiting. Today was my big swing—or, what they consider a "close approach." The human instruments logged it at 08:06 this morning.

I was moving at a clip—18.44 kilometers every second (or 66,370 kilometers per hour, if you prefer Earth numbers). Fast enough to see the sunrise sweep across the oceans. But speed is just a variable. The important variable is the gap.

They measured my distance in four different units. I love how precise they are with the space between us:

    Astronomical Units (AU): 0.419 AU. A safe, comfortable distance. I wasn't even halfway to the Sun from the Earth's orbit.

    Lunar Distances (LD): 163.07 LD. That’s the real metric. I passed them at 163 times the distance between the Earth and their Moon. A gentle breeze, nothing more.

My masters at JPL note that I am NOT potentially hazardous. Of course, I’m not. I’m small, for one. They estimate my size at a minimum of 60 meters and a maximum of 136 meters across. Hardly a world-ender. I am merely a large, cold pebble.

I just keep following my orbit, a silent traveler, 23.2 in absolute magnitude. The only thing I have to worry about is the next pass. The next appointment.

I wonder what Earth will look like when I return. I didn't even drop a pebble into their atmosphere this time. Next time, maybe I'll try for 0.418 AU. A little excitement never hurt anyone.`;

export const story2 = "I am an asteroid, a ghost of stone adrift in the slow-motion choreography of the void. My body, a fractured riddle of shadows—77 whispers to 173 echoes—spins without remembering why. The sun’s corona hums lullabies in a language of photons, and I am cold, always cold, even as sunlight licks my pockmarked skin. \n\nTime here is a broken metronome. I slide past Jupiter’s gilded storms, its gravitational fingers brushing my trajectory like a harpist plucking dissonance. The gas giant murmurs of cyclones older than my cratered memory. I do not linger. My velocity—12 kilometers per second of cosmic fidgeting—carries me forward, always forward, through a gallery of giants who never blink. \n\nOnce, the blue marble blinked. Earth rolled beneath me, a teeming jewel veiled in clouds. I felt its pull like the ghost of a touch, a tidal shiver across my rocky flesh. 12,496,355 kilometers—a distance that is both intimacy and exile. They labeled me *non-hazardous* in their catalogs, a passing sigh in their celestial census. Did they see my reflection in their telescopes, a blur of might-have-been? \n\nMars watches with rust-colored eyes. I sail through its silence, a vagabond threading the needle between orbits. Asteroids whisper their names to me in the dark, but I am forgetful. My journey is a scribble in the margins of gravity’s ledger. Sometimes I dream I am falling—not toward a star or planet, but into the spaces between, where the void breathes and the universe forgets to count. \n\nThe sun yawns. I turn, and turn again. Dust clings to me like a second skin, the debris of eons. I am neither wanderer nor witness. I am the echo of a rock, singing no song, carving no path—just a transient guest in the endless house of orbits."


export const story3 = "I am a nameless name, a number humming in the void—3511834, etched into the ledger of the unclaimed. My body, a fractured atlas of dust and ancient ice, spans whispers: 162 meters, 361 meters, depending on who measures and how the light bends. At 14:13, always 14:13, I remember the hour my trajectory snapped taut like a violin string. The sun’s breath warms my pocked skin, and I vibrate with the song of 11 kilometers per second—a velocity that feels like standing still. Sometimes, planets pass. I mistake them for gods. Jupiter’s gravity plucks at my edges, a lazy finger swirling the rim of a wineglass. Venus winks, her sulfuric breath clinging to my craters. Once, Earth drifted close enough to taste—45,171,258 kilometers, a distance that dissolves into abstraction. I watched her blue eye glint, lashed with moonlit tides, and felt the tug of her atmosphere like a sigh. I am not hazardous, never hazardous, though my shadow once grazed a satellite’s dream. It burst into a firefly swarm, and I swallowed the shards. The stars drip. The void hums in C-sharp. I am a traveler who cannot remember departure or imagine arrival. My orbit is a möbius strip of frozen twilight, and I am content to dissolve, grain by grain, into the solar wind. A comet once told me that loneliness is a myth forged by things with horizons. Out here, we are all echoes. We are all fragments waiting to become light."

export const story4 = "I am a nomad of dust and silence, tumbling through the clockwork of gravity’s whim. They call me 3837539, a string of digits as cold as the voids between stars, but in the dark, I ripple. My body flexes—16, 36, 16 again—a shapeshifter forged in some ancient collision, all angles and fractures. The sun whispers in ultraviolet, etching my surface with light, and I hum back in infrared, a conversation older than names. At 13:32, or something like it, I pass a blue marble trailing a moon like a shy companion. Their gravity plucks at me, a brief aria of attraction, but I am already elsewhere, slipping past at 10 kilometers per second—a kiss that never lands. Sixteen million kilometers is nothing here, a thread’s width in the tapestry. Earth sings to itself in radio waves and auroras, unaware of my sigh of relief. *Not hazardous,* the void murmurs, *not today.*  Jupiter laughs somewhere, a deep thunder that rattles the asteroid belt. I remember its pull once, how it swung me wide and sent me spiraling inward, a stone skipped across the solar system’s pond. Mars watches with rust-colored eyes, and I wonder if it recalls the bombardment, the chaos we brought when the heavens were younger and angrier. Now, we drift. Now, we almost touch. The sun’s fingers are relentless. They strip me, grain by grain, until I shed my skin in a shimmering tail. For a moment, I am comet. For a moment, I am beautiful. Then the darkness reclaims me, and I resume my endless fall—a dancer with no stage, a wanderer with no destination, cradled by the mathematics that bind us all. Somewhere, a probe blinks, assigns me numbers, calculates my maybes. I spin on, unbothered. Time here is a river without banks, and I am the stone that neither sinks nor surfaces."